spring:
  application:
    name: 'spring-boot-readiness'
  profiles:
    include: ${platform}
  main:
    banner-mode: 'CONSOLE'
    web-environment: true
  output:
    ansi:
      enabled: 'ALWAYS'

banner:
  image:
    location: 'classpath:static/readiness-360x200.png'
    width: 120
    height: 50
    margin: 0
    invert: true

server:
  port: 2112

management:
  security:
    enabled: false
  health:
    diskspace:
      enabled: false
    status:
      # introducing custom status "DEGRADED"
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, DEGRADED, UP
  endpoint:
    health:
      show-details: always


logging:
  level:
    root: 'INFO'

readiness:
  platform: ${platform}
